services:
  mosquitto:
    image: eclipse-mosquitto:2.0.22
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  influxdb:
    image: influxdb:2.8.0
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
      - ./influx_conf:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxUser
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxPass
      - DOCKER_INFLUXDB_INIT_ORG=piOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=piBucket
    restart: always

  node-red:
    image: nodered/node-red:4.1.2-22
    volumes:
      - ./node_red_data:/data
    depends_on:
      - mosquitto
      - influxdb
    restart: always

  grafana:
    image: grafana/grafana-oss:12.4.0-20252087470-ubuntu
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    depends_on:
      - influxdb
    restart: always

  traefik:
    image: traefik:v3.6.4-nanoserver-ltsc2022
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    depends_on:
      - node-red
      - grafana
    restart: always

